import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
const API=import.meta.env.VITE_API_URL || 'http://localhost:3000/api';
async function request(path, options={}) { const headers = options.body ? { 'Content-Type': 'application/json' } : {}; const r=await fetch(API+path,{...options,headers}); const data=await r.json(); if(!r.ok) throw new Error(data.error?.message||'Request failed'); return data; }
const next={pending:['running','failed'],running:['completed'],completed:[],failed:[]};
function App(){const [jobs,setJobs]=useState([]),[meta,setMeta]=useState({}),[counts,setCounts]=useState({}),[filters,setFilters]=useState({search:'',status:'',type:''}),[page,setPage]=useState(1),[form,setForm]=useState({title:'',type:'email',payload:''}),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[modal,setModal]=useState(null),[confirm,setConfirm]=useState(null);
 const load=async()=>{setBusy(true);setError('');try{const p=new URLSearchParams({page,limit:6,...Object.fromEntries(Object.entries(filters).filter(([,v])=>v))});const list=await request('/jobs?'+p);setJobs(list.data);setMeta(list.meta);setCounts(list.counts)}catch(e){setError(e.message)}finally{setBusy(false)}};useEffect(()=>{const t=setTimeout(load,filters.search?1000:0);return()=>clearTimeout(t)},[page,filters]);
 const setFilter=(k,v)=>{setPage(1);setFilters(f=>({...f,[k]:v}))}; const create=async e=>{e.preventDefault();if(!form.title.trim())return setError('A job title is required.');let payload=null;try{payload=form.payload?JSON.parse(form.payload):null}catch{return setError('Payload must be valid JSON.')}setBusy(true);try{await request('/jobs',{method:'POST',body:JSON.stringify({...form,title:form.title.trim(),payload})});setForm({title:'',type:'email',payload:''});setNotice('Job created successfully.');load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const update=async status=>{setBusy(true);try{await request(`/jobs/${modal.id}/status`,{method:'PATCH',body:JSON.stringify({status})});setModal(null);setNotice('Status updated.');load()}catch(e){setError(e.message)}finally{setBusy(false)}}; const del=async()=>{setBusy(true);try{await request(`/jobs/${confirm.id}`,{method:'DELETE'});setConfirm(null);if(jobs.length===1&&page>1)setPage(page-1);else load();setNotice('Job deleted.')}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <main><section className="hero"><div><p className="eyebrow">JOB OPERATIONS</p><h1>Manage your jobs,<br/><i>effortlessly.</i></h1><p className="sub">A refined workspace for tracking every task from creation to completion.</p></div><form onSubmit={create} className="create"><h2>Create a job</h2><input placeholder="What needs to be done?" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{['email','report','data-processing','notification'].map(x=><option key={x}>{x}</option>)}</select><input placeholder={'Optional JSON payload'} value={form.payload} onChange={e=>setForm({...form,payload:e.target.value})}/><button disabled={busy}>Create job <span>→</span></button></form></section>
 {notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}{error&&<div className="error">{error}<button onClick={()=>setError('')}>×</button></div>}
 <section className="dashboard"><div className="section-head"><div><p className="eyebrow">OVERVIEW</p><h2>Your job activity</h2></div><span>{counts.all||0} jobs total</span></div><div className="counts">{[['','All'],['pending','Pending'],['running','Running'],['completed','Completed'],['failed','Failed']].map(([key,label])=><button className={filters.status===key?'active '+key:key} onClick={()=>setFilter('status',key)} key={label}><small>{label}</small><strong>{key?counts[key]||0:counts.all||0}</strong></button>)}</div>
 <div className="filters"><input aria-label="Search jobs" placeholder="Search by job title..." value={filters.search} onChange={e=>setFilter('search',e.target.value)}/><select value={filters.type} onChange={e=>setFilter('type',e.target.value)}><option value="">All types</option>{['email','report','data-processing','notification'].map(x=><option key={x}>{x}</option>)}</select><button className="clear" onClick={()=>{setFilters({search:'',status:'',type:''});setPage(1)}}>Clear filters</button></div>
 {busy?<div className="state">Loading your jobs…</div>:jobs.length?<><div className="grid">{jobs.map(job=><article className="job" key={job.id}><div className="jobtop"><span className={'badge '+job.status}>{job.status}</span><button aria-label="Delete job" onClick={()=>setConfirm(job)}>×</button></div><h3>{job.title}</h3><p className="id">{job.id.slice(0,18)}…</p><div className="details"><span>{job.type}</span><span>{new Date(job.createdAt).toLocaleDateString()}</span></div><button className="change" disabled={!next[job.status].length} onClick={()=>setModal(job)}>{next[job.status].length?'Change status':'Final status'}</button></article>)}</div><div className="pagination"><button disabled={page===1} onClick={()=>setPage(page-1)}>← Previous</button><span>Page {meta.page} of {meta.totalPages||1}</span><button disabled={page>=meta.totalPages} onClick={()=>setPage(page+1)}>Next →</button></div></>:<div className="state"><h3>No jobs found</h3><p>Create a job or adjust your filters to see results here.</p></div>}</section>
 {modal&&<div className="overlay"><div className="dialog"><button className="x" onClick={()=>setModal(null)}>×</button><p className="eyebrow">CHANGE STATUS</p><h2>{modal.title}</h2><p>Select the next step for this job.</p><div className="choices">{next[modal.status].map(s=><button key={s} className={s} onClick={()=>update(s)} disabled={busy}>{s}</button>)}</div></div></div>}{confirm&&<div className="overlay"><div className="dialog"><p className="eyebrow">DELETE JOB</p><h2>Remove this job?</h2><p>“{confirm.title}” will be permanently deleted.</p><div className="choices"><button onClick={()=>setConfirm(null)}>Cancel</button><button className="failed" onClick={del} disabled={busy}>Delete job</button></div></div></div>}</main>}; createRoot(document.getElementById('root')).render(<App/>);
